
import {user} from '../tempo/user'

export const jobsarray=[{
    id:"axfd",
    owner: user,									
    business: 	"The Pump House",
    description:	"We are looking for a Kitchen Porter for our busy restaurant in ce",
    position:	"Kitchen Porter",			
    pay:		10,
    lat: 50.8211649,
    lng: -0.1376229,		
    isTemporanery:	true,
    duration:	"12.30 - 17.30",
},
{
  id:"sdasda",	
  owner: user,									
  business: 	"Grow 40 2",
  description:	"We are looking for a Kitchen Porter for our busy restaurant in ce",
  position:	"Chef",			
  pay:		9,
  lat: 50.8257275,
  lng: -0.1409788,
  isTemporanery:	true,
  duration:	"19.30 - 00.30",
},
{
id:"dsadsa",	
owner: user,									
business: 	"Kooks Restaurant",
description:	"Maecenas ut dui non mauris scelerisque euismod ac sed augue. Vivamus faucibus elementum suscipit. Donec in convallis nunc. []a egestas ipsum id augue vestibulum, sed venenatis sapien pharetra. Fusce gravida turpis nec ipsum egestas, mattis rhoncus ipsum finibus. Aenean condimentum eget ligula sit amet porttitor. Interdum et malesuada fames ac ante ipsum primis in faucibus. Phasellus vulputate, quam eget interdum facilisis, sem erat varius justo, et pulvinar leo mi vel diam. Morbi nec quam iaculis, accumsan ante ut, porta turpis. Curabitur dictum nisl eget erat vulputate, sit amet varius purus venenatis. Pellentesque molestie sodales consequat. Maecenas sagittis []a non augue elementum, vel tempus elit maximus. Donec elementum lectus sem, ut bibendum felis placerat eu. Nam in orci tellus. Aliquam quis lacus fermentum, mattis arcu id, laoreet ligula. Cras pharetra condimentum euismod.",
position:	"Commis Chef",			
pay:		7,	
lat: 50.8254839,
lng: -0.1408186,	
isTemporanery:	true,
duration:	"13.30 - 21.30",
},
{
id:"sasasx",	
owner: user,									
business: 	"Wasabi 4",
description:	"We are looking for a Kitchen Porter for our busy restaurant in ce",
position:	"Kitchen Porter",			
pay:		7.83,
lat: 50.8234695,
lng: -0.1457976,	
isTemporanery:	true,
duration:	"12.30 - 17.30",
},
{
id:"sasasxxx",	
owner: user,									
business: 	"Moshimo 5",
description:	"We are looking for a Kitchen Porter for our busy restaurant in ce",
position:	"Head Chef",			
pay:		13,
lat: 50.8206376,
lng: -0.1428548,		
isTemporanery:	true,
duration:	"8.30 - 00.30",
}
,{
id:"axfd",	
owner: user,									
business: 	"Le Pan Quotidien 6",
description:	"We are looking for a Kitchen Porter for our busy restaurant in ce",
position:	"Kitchen Porter",			
pay:		10,	
lat: 50.8206376,
lng: -0.1928548,
isTemporanery:	true,
duration:	"12.30 - 17.30",
},{
id:"axfd",	
owner: user,									
business: 	"The Pump House",
description:	"We are looking for a Kitchen Porter for our busy restaurant in ce",
position:	"Kitchen Porter",			
pay:		10,
lat: 50.8211649,
lng: -0.1376229,		
isTemporanery:	true,
duration:	"12.30 - 17.30",
},
{
id:"sdasda",
owner: user,										
business: 	"Grow 40 2",
description:	"We are looking for a Kitchen Porter for our busy restaurant in ce",
position:	"Chef",			
pay:		9,
lat: 50.8257275,
lng: -0.1409788,
isTemporanery:	true,
duration:	"19.30 - 00.30",
},
{
id:"dsadsa",
owner: user,										
business: 	"Kooks Restaurant",
description:	"We are looking for a Kitchen Porter for our busy restaurant in ce",
position:	"Commis Chef",			
pay:		7,	
lat: 50.8254839,
lng: -0.1408186,	
isTemporanery:	true,
duration:	"13.30 - 21.30",
},
{
id:"sasasx",
owner: user,										
business: 	"Wasabi 4",
description:	"We are looking for a Kitchen Porter for our busy restaurant in ce",
position:	"Kitchen Porter",			
pay:		7.83,
lat: 50.8234695,
lng: -0.1457976,	
isTemporanery:	true,
duration:	"12.30 - 17.30",
},
{
id:"sasasxxx",	
owner: user,									
business: 	"Moshimo 5",
description:	"We are looking for a Kitchen Porter for our busy restaurant in ce",
position:	"Head Chef",			
pay:		13,
lat: 50.8206376,
lng: -0.1428548,		
isTemporanery:	true,
duration:	"8.30 - 00.30",
}
,{
id:"axfd",
owner: user,										
business: 	"Le Pan Quotidien 6",
description:	"We are looking for a Kitchen Porter for our busy restaurant in ce",
position:	"Kitchen Porter",			
pay:		10,	
lat: 50.8206376,
lng: -0.1928548,
isTemporanery:	true,
duration:	"12.30 - 17.30",
},{
id:"axfd",		
owner: user,								
business: 	"Last3",
description:	"We are looking for a Kitchen Porter for our busy restaurant in ce",
position:	"Kitchen Porter",			
pay:		10,
lat: 30.8211649,
lng: -0.1376229,		
isTemporanery:	true,
duration:	"12.30 - 17.30",
},
{
id:"sdasda",	
owner: user,									
business: 	"Grow 40 2",
description:	"We are looking for a Kitchen Porter for our busy restaurant in ce",
position:	"Chef",			
pay:		9,
lat: 30.8257275,
lng: -0.1409788,
isTemporanery:	true,
duration:	"19.30 - 00.30",
},
{
id:"dsadsa",	
owner: user,									
business: 	"Last",
description:	"We are looking for a Kitchen Porter for our busy restaurant in ce",
position:	"Commis Chef",			
pay:		7,	
lat: 30.8254839,
lng: -0.1408186,	
isTemporanery:	true,
duration:	"13.30 - 21.30",
},
{
id:"sasasx",	
owner: user,									
business: 	"Wasabi 4",
description:	"We are looking for a Kitchen Porter for our busy restaurant in ce",
position:	"Kitchen Porter",			
pay:		7.83,
lat: 30.8234695,
lng: -0.1457976,	
isTemporanery:	true,
duration:	"12.30 - 17.30",
},
{
id:"sasasxxx",	
owner: user,									
business: 	"Moshimo 5",
description:	"We are looking for a Kitchen Porter for our busy restaurant in ce",
position:	"Head Chef",			
pay:		13,
lat: 30.8206376,
lng: -0.1428548,		
isTemporanery:	true,
duration:	"8.30 - 00.30",
}
,{
id:"axfd",	
owner: user,									
business: 	"Le Pan Quotidien 6",
description:	"We are looking for a Kitchen Porter for our busy restaurant in ce",
position:	"Kitchen Porter",			
pay:		10,	
lat: 30.8206376,
lng: -0.1928548,
isTemporanery:	true,
duration:	"12.30 - 17.30",
},
  ]